import {SCREEN_WIDTH} from '../../constants/index';
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  gridView: {
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    marginTop: 16,
    backgroundColor: 'transparent',
    // paddingLeft: SCREEN_WIDTH * 0.,
  },
  circleView: {
    position: 'absolute',
    borderRadius: 70 / 2,
    height: 54,
    width: 54,
    left: 0,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 1)',
    display: 'flex',
    justifyContent: 'center',
    padding: 8,
    zIndex: 20,
    borderColor: '#00B4AC',
    borderWidth: 1,
  },
  circleText: {
    textAlign: 'left',
    fontSize: 22,
    lineHeight: 26,
    color: '#000000',
  },
  circleView1: {
    position: 'absolute',
    borderRadius: 70 / 2,
    height: 28,
    width: 28,
    left: 36,
    top: 44,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 1)',
    display: 'flex',
    justifyContent: 'center',
    // padding: 8,
    zIndex: 20,
    borderColor: '#00B4AC',
    borderWidth: 1,
  },
  circleText1: {
    textAlign: 'left',
    fontSize: 22,
    lineHeight: 26,
    color: '#000000',
  },
  rectangleView: {
    display: 'flex',
    flex: 1,
    borderStyle: 'solid',
    borderRadius: 8,
    borderColor: '#707070',
    backgroundColor: '#FFFFFF',
    marginLeft: 32,
  },
  itemContainer: {
    display: 'flex',
    flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    height: 80,
  },
  surahType: {
    textAlign: 'justify',
    fontSize: 8,
    color: '#1D2226',
  },
  surahName: {
    textAlign: 'justify',
    fontSize: 16,
    color: 'black',
  },
  surahIndex: {
    display: 'flex',
    flexDirection: 'row',
    marginRight: 16,
    paddingTop: 4,
    textAlign: 'center',
    fontSize: 16,
    borderStyle: 'solid',
    width: 32,
    height: 32,
    borderRadius: 10,
    borderWidth: 1,
  },
});
export default styles;
