import {SCREEN_WIDTH} from '../constants/index';
import {Platform, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityIndicator: {
    alignItems: 'center',
    height: 80,
  },
  splashText: {
    color: '#FAFAFA',
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '500',
  },
  languageAppText: {
    color: '#1CB4AC',
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 65,
    top: 8,
    fontWeight: '500',
  },
  selectionLanguageText: {
    color: '#3B3B3B',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 65,
    top: 8,
    fontWeight: '400',
  },
  homeView: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    zIndex: 50,
  },
  searchContainer: {
    margin: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    width: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
  },
  searchBarView: {
    display: 'flex',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderRadius: 18,
    marginTop: 20,
    backgroundColor: '#FFFFFF',
    alignSelf: 'flex-start',
    marginHorizontal: 28,
    width: '90%',
  },
  searchBar__unclicked: {
    padding: 10,
    flexDirection: 'row',
    width: '95%',
    backgroundColor: 'transparent',
    borderRadius: 15,
    alignItems: 'center',
  },
  searchBar__clicked: {
    padding: 10,
    flexDirection: 'row',
    width: '80%',
    backgroundColor: 'transparent',
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputSearch: {
    fontSize: 20,
    marginLeft: 10,
    width: '90%',
  },
  selectionContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingTop: Platform.OS === 'ios' ? (SCREEN_WIDTH / 10) * 2 : 10,
    paddingHorizontal: SCREEN_WIDTH * 0.03,
  },
  readingcontainer: {
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    borderStyle: 'solid',
    borderWidth: 2,

    flexDirection: 'row-reverse',
    width: 'auto',
    flexWrap: 'wrap',
    borderRadius: 16,
    marginTop: 8,
    alignContent: 'center',
  },
  listContainer: {marginBottom: 128},
  listDetailContainer: {
    width: '100%',
    paddingleft: 64,
  },
  itemContainer: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    paddingVertical: 16,
    borderColor: '#ffffff',
    paddingHorizontal: 12,
    marginVertical: 4,
    display: 'flex',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
  },
  itemText: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    color: '#FFFFFF',
  },
  bismillahView: {
    borderRadius: 8,
    paddingVertical: 16,
    paddingHorizontal: 12,
    marginTop: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row-reverse',
  },
  bismillahText: {
    textAlign: 'center',
    color: '#D49C35',
    fontSize: 24,
    fontFamily: 'Arial',
    fontWeight: '700',
    letterSpacing: 3,
  },
  textIndex: {
    fontSize: 20,
    borderWidth: 2,
    borderStyle: 'solid',
  },
  homeScreenButton: {
    display: 'flex',
    flex: 1,
    paddingBottom: 36,
    marginLeft: 4,
    paddingTop: 36,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#707070',
    backgroundColor: 'rgba(59,59,59,0.5)',
  },
  homeScreenImageView: {
    position: 'absolute',
    right: 12,
    top: 8,
    alignSelf: 'flex-end',
  },
  homeScreenText: {
    fontSize: 16,
    fontWeight: '300',
    lineHeight: 58,
    textAlign: 'center',
    color: '#ffffff',
  },
  segementedView: {
    borderRadius: 48,
    marginTop: 16,
    backgroundColor: '#FFFFFF',
  },
  tabsContainerStyle: {
    borderRadius: 24,
    padding: 2,
    backgroundColor: '#FFFFF',
  },
  tabStyle: {
    borderRadius: 24,
    borderColor: 'rgba(255,255,255,0)',
  },
  activeTabStyle: {
    backgroundColor: '#C7AA35',
  },
  tabTextStyle: {textAlign: 'left', fontSize: 16, color: '#00B4AC'},
  activeTabTextStyle: {
    textAlign: 'left',
    fontSize: 16,
    color: '#FFFFFF',
  },
  mushafView: {
    paddingVertical: 16,
    paddingBottom: 64,
    borderRadius: 16,
    marginTop: 36,
    backgroundColor: 'rgba(255,255,255,0.4)',
  },
  elementTextStyle: {
    textAlign: 'center',
    fontSize: 24,
    color: '#1A1A1A',
    letterSpacing: 0,
    fontFamily: 'Arial',
  },
  indexTextStyle: {
    fontSize: 20,
    color: '#C7AA35',
  },
  paraSurahTitleView: {
    backgroundColor: 'rgba(255,255,255,0.4)',
    paddingVertical: 8,
    marginTop: 8,
  },
  paraSurahTitleText: {
    textAlign: 'center',
    fontSize: 24,
    color: '#D49C35',
    fontWeight: '700',
    letterSpacing: 3,
  },
});

export default styles;
