import {SCREEN_WIDTH} from '../constants/index';
import {Platform, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
  },
  activityIndicator: {
    alignItems: 'center',
    height: 80,
  },
  splashText: {
    color: '#FAFAFA',
    // marginTop: 8,
    // marginLeft: 8,
    textAlign: 'center',
    fontSize: 22,
    lineHeight: 29,
    fontWeight: '500',
  },
  languageAppText: {
    color: '#1CB4AC',
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 65,
    top: 8,
    fontWeight: '500',
  },
  selectionLanguageText: {
    color: '#3B3B3B',
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 65,
    top: 8,
    fontWeight: '400',
  },
  selectionContainer: {
    display: 'flex',
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-start',
    paddingTop: Platform.OS === 'ios' ? (SCREEN_WIDTH / 10) * 2 : 10,
    paddingHorizontal: SCREEN_WIDTH * 0.03,
  },
  readingcontainer: {
    flex: 1,
    paddingLeft: 0,
    backgroundColor: '#ffff',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    marginTop: 100,
  },
  listContainer: {
    // width: '100%',
    // paddingHorizontal: SCREEN_WIDTH * 0.4,
    // marginTop: 100,
    // borderStyle: 'solid',
    // borderWidth: 2,
    // borderColor: 'pink',
  },
  listDetailContainer: {
    width: '100%',
    paddingleft: 64,
  },
  itemContainer: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    paddingTop: 16,
    borderColor: '#ff00ff',
    overflow: 'hidden',
    shadowColor: '#0b1a13',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 0.8,
    shadowRadius: 128,
    paddingHorizontal: 12,
    paddingBottom: 8,
    marginVertical: 4,
    marginHorizontal: 4,
    display: 'flex',
    flex: 1,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  itemText: {
    flex: 1,
    textAlign: 'right',
    fontSize: 20,
  },
  bismillahText: {
    textAlign: 'center',
    marginTop: 32,
    fontWeight: 'bold',
    marginHorizontal: 16,
    marginVertical: 16,
    fontSize: 20,
  },
  textIndex: {
    fontSize: 20,
    borderWidth: 2,
    borderStyle: 'solid',
  },
  nestedText: {
    textAlign: 'right',
    fontSize: 20,
    lineHeight: 40,
  },
  mushafView: {
    display: 'flex',
    flex: 1,
    justifyContent: 'flex-start',
    flexDirection: 'row-reverse',
    width: 'auto',
    flexWrap: 'wrap',
    paddingHorizontal: 8,
  },
  homeScreenButton: {
    display: 'flex',
    flex: 1,
    paddingBottom: 36,
    marginLeft: 4,
    paddingTop: 36,
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#707070',
    backgroundColor: 'rgba(59,59,59,0.5)',
  },
  homeScreenImageView: {
    position: 'absolute',
    right: 12,
    top: 8,
    alignSelf: 'flex-end',
  },
  homeScreenText: {
    fontSize: 16,
    fontWeight: '300',
    lineHeight: 58,
    textAlign: 'center',
    color: '#ffffff',
  },
});
const textStyles = StyleSheet.create({
  demo: {
    textShadowOffset: {width: 3, height: 3},
    textShadowColor: '#464646',
    textShadowRadius: 10,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#000000',
    paddingLeft: 8,
    marginLeft: 16,
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#0000',
  },
});

export {styles, textStyles};
